version: "3"
services:
  development:
    build:
      context: . # Specify the base directory to find all docker related files
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # Don't overwrite "/node_modules" when symlinking to the project outside the container.
      - .:/app # Symlink the entire project folder to our working directory.
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["yarn", "test"]
    environment:
      CI: "true"
    volumes:
      - /app/node_modules
      - .:/app